# Takes message (generated by aws.emr eventbridge and sends it to pagerduty if it's state is FAILED and the 'message' contains 'trigger_text')
import boto3
import json
import logging

logger = logging.getLogger()

ses_client = boto3.client('ses', 'us-east-1')

def lambda_handler(event, context):

    message = event['detail']['message']
    state   = event['detail']['state']
    pagerduty_email = 'qpp-final-scoring@cms-qpp.pagerduty.com'
    trigger_text = 'FS-prod-Timer'
    
    if state == "FAILED":
        if trigger_text in message:
            response = ses_client.send_email(
                Source='qpp-final-scoring-devops@semanticbits.com',
                Destination={
                    'ToAddresses': [ pagerduty_email
                    ],
                    'CcAddresses': ['jeremy.page@semanticbits.com']
                    },
                    Message={
                        'Subject': {
                            'Data'    : 'EMR Alert',
                            'Charset' : 'UTF-8'
                    },
                    'Body': {
                        'Text': {
                            'Data'    : 'EMR Alert Notification',
                            'Charset' : 'UTF-8'
                        },
                        'Html': {
                            'Data'    : message,
                            'Charset' : 'UTF-8'
                        }
                    }
                }
            )
    return message


